# Generated by Django 6.0.5 on 2026-05-20 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cedula', models.CharField(max_length=9, unique=True)),
                ('celular', models.CharField(max_length=12)),
                ('direccion', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('direccionIP', models.GenericIPAddressField(protocol='IPv4', unique=True)),
                ('saldo', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(default='Activo', max_length=20)),
                ('borrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(max_length=20)),
                ('precioUSD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('velocidad_subida', models.DecimalField(decimal_places=2, max_digits=10)),
                ('velocidad_bajada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('borrado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoUSD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulo', models.CharField(max_length=30)),
                ('mensaje', models.TextField()),
                ('error', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('idPersonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montoUSD', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tasa', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pagoUSD', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/%Y/%m/%d/')),
                ('idCliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente')),
                ('idPersonal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='idPlan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plan'),
        ),
    ]
