# Generated by Django 6.0.5 on 2026-05-26 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_pago_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='pagoUSD',
        ),
        migrations.AddField(
            model_name='pago',
            name='metodo',
            field=models.CharField(choices=[('Transferencia', 'Transferencia'), ('Pago Móvil', 'Pago Móvil'), ('Zelle', 'Zelle'), ('Efectivo Bs', 'Efectivo Bs'), ('Efectivo $', 'Efectivo $')], default='Metodo', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Solvente', 'Solvente'), ('Exonerado', 'Exonerado'), ('Pendiente', 'Pendiente'), ('Desconectado', 'Desconectado')], default='Solvente', max_length=20),
        ),
    ]
