# Generated by Django 6.0.5 on 2026-05-26 04:35

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_pago_pagousd_pago_metodo_alter_cliente_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='tasa',
            field=models.DecimalField(decimal_places=2, default=core.models.obtener_tasa_actual, max_digits=10),
        ),
    ]
