# Generated by Django 6.0.5 on 2026-05-29 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_pago_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='comprobante',
            field=models.ImageField(default='', upload_to='comprobantes/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
