# Generated by Django 6.0.5 on 2026-05-31 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_cliente_cedula_alter_cliente_direccionip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('Solvente', 'Solvente'), ('Exonerado', 'Exonerado'), ('Pendiente', 'Pendiente'), ('Desconectado', 'Desconectado')], max_length=20),
        ),
    ]
