# Generated by Django 6.0.5 on 2026-06-04 02:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_pago_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='fechaRegistro',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
